In [1]:
from my_dataset import gen_dataset
from my_model import SimpleSleepPPGModel

import torch
from torch import nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from torchsummary import summary

# 데이터셋 준비
print("Data loading ... ", end='')
full_dataset = gen_dataset(train_or_test='default')
print("done !")

# Train, Validation, Test Split
total_size = len(full_dataset)
train_size = int(0.8 * total_size)
val_size = int(0.1 * total_size)
test_size = total_size - train_size - val_size  # 나머지는 test에 할당
train_dataset, val_dataset, test_dataset = random_split(full_dataset, [train_size, val_size, test_size])

batch_size = 4
generator1 = torch.Generator().manual_seed(42)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, generator=generator1)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, generator=generator1)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, generator=generator1)

Data loading ... done !


In [35]:
import torch
import numpy as np
from my_model import SimpleSleepPPGModel

cnt_0 = 0
cnt_1 = 0

for signal, label in train_loader:
    pass

# 모델 초기화
device = torch.device("cuda")
model = SimpleSleepPPGModel().to(device)
signal_torch = signal.to(device)
label_torch = label.to(device)

predicted_label = model(signal_torch)

_, predicted_label_idx = torch.max(predicted_label, axis=1)
_, true_label_idx = torch.max(label_torch, axis=1)

# criterion = nn.BCEWithLogitsLoss()
criterion = nn.CrossEntropyLoss()
loss = criterion(predicted_label.float(), true_label_idx)
# corr = (predicted_label_idx == true_label_idx).sum().item()

# print(predicted_label)
# print(label)

# print(predicted_label_idx)
# print(true_label_idx)

# print(corr)

In [32]:
import torch
import torch.nn as nn

# 모델 출력 (로짓)
outputs = torch.tensor([[1.5, 2.0, 0.1],   # 샘플 1의 클래스 점수
                        [0.5, 1.5, 2.5]])  # 샘플 2의 클래스 점수

# 정답 라벨 (클래스 인덱스)
labels = torch.tensor([1, 2])  # 첫 번째 샘플 정답은 1번 클래스, 두 번째는 2번 클래스

# 손실 함수 정의
criterion = nn.CrossEntropyLoss()

# 손실 계산
loss = criterion(outputs, labels)
print("Loss:", loss.item())


Loss: 0.48535045981407166


In [14]:
predicted_label_idx = torch.max(predicted_label, axis=1)

In [10]:
print(predicted_label)
print(label)

tensor([[0.5747, 0.4253],
        [0.3924, 0.6076]], device='cuda:0', grad_fn=<SoftmaxBackward0>)
tensor([[0, 1],
        [1, 0]])


In [32]:
label_torch

tensor([[1, 0],
        [1, 0],
        [0, 1],
        [0, 1]], device='cuda:0')

In [30]:
_, predicted = torch.max(predicted_label, 1)
(predicted == label_torch).sum().item()
# total_train += labels.size(0)

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

In [23]:
model(signal_torch)

tensor([[0.5317, 0.4683],
        [0.5547, 0.4453],
        [0.7365, 0.2635],
        [0.4336, 0.5664]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [40]:
import os
import numpy as np
path_load = 'Y:/MESA_0.7.0/ppg_preprocessed_npy'
labels = np.load(os.path.join(path_load, "label_ins_hc.npy"))

In [48]:
labels[160]

0.0

In [47]:
full_dataset[160]

(tensor([[1.7117, 2.5175, 3.2185,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([1, 0]))

In [45]:
train_dataset[5]

(tensor([[1.7117, 2.5175, 3.2185,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([1, 0]))

In [34]:
train_dataset.indices

[55,
 64,
 58,
 15,
 65,
 160,
 12,
 164,
 8,
 185,
 57,
 146,
 172,
 63,
 182,
 134,
 159,
 7,
 6,
 54,
 28,
 117,
 93,
 169,
 126,
 112,
 97,
 128,
 144,
 67,
 22,
 56,
 69,
 171,
 82,
 101,
 115,
 154,
 186,
 29,
 37,
 81,
 175,
 60,
 155,
 35,
 130,
 158,
 85,
 47,
 70,
 176,
 161,
 113,
 44,
 98,
 180,
 49,
 51,
 162,
 137,
 86,
 191,
 188,
 89,
 127,
 166,
 77,
 193,
 30,
 107,
 40,
 20,
 36,
 120,
 32,
 73,
 3,
 184,
 124,
 11,
 62,
 23,
 78,
 72,
 190,
 90,
 116,
 106,
 147,
 94,
 132,
 52,
 38,
 152,
 88,
 83,
 156,
 149,
 80,
 192,
 79,
 91,
 189,
 10,
 123,
 122,
 66,
 135,
 108,
 0,
 74,
 183,
 45,
 136,
 39,
 95,
 187,
 129,
 18,
 125,
 27,
 114,
 111,
 148,
 121,
 178,
 61,
 139,
 46,
 143,
 174,
 109,
 4,
 99,
 141,
 163,
 50,
 68,
 41,
 181,
 2,
 13,
 170,
 96,
 76,
 110,
 196,
 43,
 105,
 140,
 177,
 153,
 194,
 34,
 53,
 151,
 179]

In [20]:
cnt_0 = 0
cnt_1 = 0

for signal, label in train_loader:
    # print(signal.shape, label)

    for label_test in label:
        if label_test == 0:
            cnt_0 += 1
        else:
            cnt_1 += 1

print(cnt_0, cnt_1)

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [4]:
import os
from sklearn.preprocessing import OneHotEncoder
import numpy as np
path_load = 'Y:/MESA_0.7.0/ppg_preprocessed_npy'
labels = np.load(os.path.join(path_load, "label_ins_hc.npy")).reshape(-1, 1)

# One-hot encoder 생성 및 적용
encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = encoder.fit_transform(labels)

In [11]:
one_hot_encoded.float()

AttributeError: 'numpy.ndarray' object has no attribute 'float'

In [7]:
type(full_dataset)

my_dataset.gen_dataset

In [6]:
full_dataset.labels

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
type(train_dataset)

torch.utils.data.dataset.Subset

In [1]:
from my_dataset import gen_dataset
from my_model import SimpleSleepPPGModel, SimpleSleepPPGModel_2

import torch
from torch import nn
import torch.optim as optim
from torch.utils.data import DataLoader


In [3]:
# 데이터셋 준비
train_dataset = gen_dataset(train_or_test='train')
test_dataset = gen_dataset(train_or_test='test')

In [4]:
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)

my_model = SimpleSleepPPGModel()

In [3]:
(3305831/(2**12)).__trunc__()

807

In [1]:
from my_model import SimpleSleepPPGModel, SimpleSleepPPGModel_2

from torchsummary import summary
my_model = SimpleSleepPPGModel()
net = my_model.cuda()
summary(net, (1, 3305831))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv1d-1          [-1, 16, 1652916]              64
       BatchNorm1d-2          [-1, 16, 1652916]              32
         MaxPool1d-3           [-1, 16, 826458]               0
            Conv1d-4           [-1, 16, 826458]             784
       BatchNorm1d-5           [-1, 16, 826458]              32
         MaxPool1d-6           [-1, 16, 413229]               0
            Conv1d-7           [-1, 16, 413229]             784
       BatchNorm1d-8           [-1, 16, 413229]              32
         MaxPool1d-9           [-1, 16, 206614]               0
           Conv1d-10           [-1, 32, 103307]           1,568
      BatchNorm1d-11           [-1, 32, 103307]              64
        MaxPool1d-12            [-1, 32, 51653]               0
           Conv1d-13            [-1, 32, 51653]           3,104
      BatchNorm1d-14            [-1, 32

In [ ]:
# 하이퍼파라미터
num_epochs = 10
learning_rate = 0.001

# 모델, 손실 함수, 옵티마이저 초기화
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = SimpleSleepPPGModel().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# 학습 루프
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for signals, labels in train_loader:
        signals, labels = signals.to(device), labels.to(device)
        
        # Forward pass
        outputs = model(signals)
        loss = criterion(outputs, labels)
        
        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()

    print(f"Epoch [{epoch + 1}/{num_epochs}], Loss: {running_loss / len(train_loader):.4f}")
